// client-vue/src/components/CreatePerformanceDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import type {
  CreatePerformanceResponse,
  DepartmentOption,
  EmployeeDirectoryListItem,
  FeishuSubjectOption,
  ScoringScheme,
} from "@/types/api.interface";
import { createPerformance, getPerformanceMonthPeriods } from "@/api/performances";
import { getAllEmployees, getDepartmentOptions, getFeishuLoginSubjects } from "@/api/employees";
import { listScoringSchemes } from "@/api/scoringSchemes";
import AssessmentMonthPicker from "@/components/performance/AssessmentMonthPicker.vue";

const open = defineModel<boolean>("open", { default: false });
const emit = defineEmits<{ success: [] }>();

type TargetType = "all" | "department" | "employee";
type Period = { periodKey: string; name: string };

const loading = ref(false);
const submitting = ref(false);
const employees = ref<EmployeeDirectoryListItem[]>([]);
const departmentOptions = ref<DepartmentOption[]>([]);
const periods = ref<Period[]>([]);
const feishuSubjects = ref<FeishuSubjectOption[]>([]);
const subjectCode = ref("");
const targetType = ref<TargetType>("employee");
const selectedEmployees = ref<string[]>([]);
const period = ref("");
const scoringSchemeId = ref("");
const schemeList = ref<ScoringScheme[]>([]);
const schemeSelectHint = ref("");
const query = ref("");
const result = ref<CreatePerformanceResponse | null>(null);
const showResult = ref(false);
const message = ref<string | null>(null);

function matchesDept(emp: EmployeeDirectoryListItem, dept: DepartmentOption): boolean {
  const did = emp.departmentId?.trim();
  if (did) return did === dept.id;
  const dn = emp.departmentName?.trim();
  const dnm = dept.name?.trim();
  return !!(dn && dnm && dn === dnm);
}

const filteredDepartmentOptions = computed(() => {
  const q = query.value.trim().toLowerCase();
  const base = [...departmentOptions.value].sort((a, b) => {
    const an = (a.name ?? a.id ?? "").toString();
    const bn = (b.name ?? b.id ?? "").toString();
    return an.localeCompare(bn, "zh-CN");
  });
  if (!q) return base;
  return base.filter((dept) => {
    const label = (dept.name ?? dept.id ?? "").toLowerCase();
    if (label.includes(q)) return true;
    return employees.value.some((e) => matchesDept(e, dept) && e.name.toLowerCase().includes(q));
  });
});

function employeesInDept(dept: DepartmentOption): EmployeeDirectoryListItem[] {
  const q = query.value.trim().toLowerCase();
  return employees.value.filter((e) => {
    if (!matchesDept(e, dept)) return false;
    if (!q) return true;
    if ((dept.name ?? "").toLowerCase().includes(q)) return true;
    return e.name.toLowerCase().includes(q);
  });
}

function deptEmployeeIds(dept: DepartmentOption): string[] {
  const ids = employees.value.filter((e) => matchesDept(e, dept)).map((e) => e.userId);
  return Array.from(new Set(ids));
}

/** 部门行复选框：有任意成员被选中即显示勾选（不要求全员），与「少选一人仍打勾」的期望一致 */
function deptHeaderChecked(dept: DepartmentOption): boolean {
  const ids = deptEmployeeIds(dept);
  return ids.some((id) => selectedEmployees.value.includes(id));
}

function toggleDeptSelectAll(dept: DepartmentOption, checked: boolean) {
  const ids = deptEmployeeIds(dept);
  if (checked) {
    selectedEmployees.value = Array.from(new Set([...selectedEmployees.value, ...ids]));
    return;
  }
  selectedEmployees.value = selectedEmployees.value.filter((id) => !ids.includes(id));
}

const filteredEmployees = computed(() => {
  const q = query.value.trim().toLowerCase();
  if (!q) return employees.value;
  return employees.value.filter(
    (e) => e.name.toLowerCase().includes(q) || (e.departmentName ?? "").toLowerCase().includes(q),
  );
});

const totalSelectedCount = computed(() => {
  if (targetType.value === "all") return new Set(employees.value.map((e) => e.userId)).size;
  return selectedEmployees.value.length;
});

const failedResults = computed(() => result.value?.results.filter((row) => !row.success) ?? []);

function schemeWeightSummary(s: ScoringScheme): string {
  const parts: string[] = [];
  if (s.performanceWeight > 0) parts.push(`绩效 ${s.performanceWeight}%`);
  if (s.cultureWeight > 0) parts.push(`文化 ${s.cultureWeight}%`);
  if (s.learningWeight > 0) parts.push(`学习 ${s.learningWeight}%`);
  return parts.length ? `${s.name}（${parts.join(" / ")}）` : s.name;
}

const allEmployeesSelected = computed(
  () =>
    filteredEmployees.value.length > 0 &&
    filteredEmployees.value.every((e) => selectedEmployees.value.includes(e.userId)),
);

watch(open, async (value) => {
  if (!value) return;
  resetForm();
  await loadFeishuSubjects();
  subjectCode.value = feishuSubjects.value[0]?.code ?? "";
  if (!subjectCode.value.trim()) {
    void loadData();
  }
});

watch(subjectCode, (code) => {
  if (!open.value || showResult.value) return;
  selectedEmployees.value = [];
  const c = (code ?? "").trim();
  if (!c) {
    employees.value = [];
    departmentOptions.value = [];
    return;
  }
  void loadData();
});

watch(targetType, () => {
  query.value = "";
  selectedEmployees.value = [];
});

function resetForm() {
  targetType.value = "employee";
  selectedEmployees.value = [];
  period.value = "";
  scoringSchemeId.value = "";
  schemeSelectHint.value = "";
  query.value = "";
  subjectCode.value = "";
  result.value = null;
  showResult.value = false;
  message.value = null;
}

async function loadFeishuSubjects() {
  try {
    const res = await getFeishuLoginSubjects();
    feishuSubjects.value = res.items || [];
  } catch {
    feishuSubjects.value = [];
  }
}

async function loadData() {
  loading.value = true;
  try {
    const code = subjectCode.value.trim();
    const [ps, schemesRes] = await Promise.all([getPerformanceMonthPeriods(), listScoringSchemes(1, 500)]);
    periods.value = ps.items ?? [];
    const allSchemes = schemesRes.list ?? [];
    schemeList.value = allSchemes.filter((s) => s.status === "enabled");
    schemeSelectHint.value =
      allSchemes.length > 0 && schemeList.value.length === 0
        ? `已拉取 ${allSchemes.length} 个评分方案，均为「停用」。请先到「评分方案」页启用后再选。`
        : "";
    if (!code) {
      employees.value = [];
      departmentOptions.value = [];
      message.value = feishuSubjects.value.length ? "请先选择飞书主体" : "未配置飞书登录主体，请联系管理员";
      return;
    }
    const [emps, deptRes] = await Promise.all([
      getAllEmployees({ subjectCode: code }),
      getDepartmentOptions({ subjectCode: code }),
    ]);
    employees.value = emps.items ?? [];
    departmentOptions.value = deptRes.items ?? [];
    message.value = null;
  } catch {
    employees.value = [];
    departmentOptions.value = [];
    periods.value = [];
    schemeList.value = [];
    schemeSelectHint.value = "";
    message.value = "加载数据失败，请重试";
  } finally {
    loading.value = false;
  }
}

function close() {
  open.value = false;
}

function toggleEmployee(userId: string, checked: boolean) {
  if (checked) {
    if (!selectedEmployees.value.includes(userId)) {
      selectedEmployees.value = [...selectedEmployees.value, userId];
    }
    return;
  }
  selectedEmployees.value = selectedEmployees.value.filter((item) => item !== userId);
}

function toggleSelectAllEmployees() {
  const ids = filteredEmployees.value.map((e) => e.userId);
  if (allEmployeesSelected.value) {
    selectedEmployees.value = selectedEmployees.value.filter((id) => !ids.includes(id));
    return;
  }
  selectedEmployees.value = Array.from(new Set([...selectedEmployees.value, ...ids]));
}

function getSelectedEmployeeIds(): string[] {
  if (targetType.value === "all") return Array.from(new Set(employees.value.map((e) => e.userId)));
  return selectedEmployees.value;
}

async function submit() {
  const employeeIds = getSelectedEmployeeIds();
  if (!subjectCode.value.trim()) {
    message.value = "请先选择飞书主体";
    return;
  }
  if (!employeeIds.length) {
    message.value = "请至少选择一名员工";
    return;
  }
  if (!period.value) {
    message.value = "请选择考核月度";
    return;
  }
  if (!scoringSchemeId.value) {
    message.value = "请选择评分方案";
    return;
  }
  submitting.value = true;
  message.value = null;
  try {
    result.value = await createPerformance({
      employeeIds,
      period: period.value,
      scoringSchemeId: scoringSchemeId.value,
      subjectCode: subjectCode.value.trim(),
    });
    showResult.value = true;
  } catch (e) {
    message.value = e instanceof Error ? e.message : "创建绩效失败";
  } finally {
    submitting.value = false;
  }
}

function finish() {
  close();
  emit("success");
}
</script>

<template>
  <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="close">
    <div class="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-md border border-border bg-card p-6 shadow-sm">
      <h2 class="text-lg font-semibold">创建绩效评估</h2>
      <p v-if="message" class="mt-2 text-sm text-destructive">{{ message }}</p>

      <template v-if="showResult && result">
        <div class="mt-4 space-y-2 text-sm">
          <p>总计：{{ result.total }} 条</p>
          <p class="text-success">成功：{{ result.successCount }} 条</p>
          <p v-if="result.failCount > 0" class="text-destructive">失败：{{ result.failCount }} 条</p>
        </div>
        <div v-if="failedResults.length > 0" class="mt-4 max-h-40 space-y-1 overflow-y-auto rounded-md border border-border p-3">
          <p v-for="(row, idx) in failedResults" :key="idx" class="text-sm text-destructive">
            {{ row.employeeName || row.employeeId }}：{{ row.error || "失败" }}
          </p>
        </div>
        <div class="mt-6 flex justify-end">
          <button type="button" class="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" @click="finish">
            完成
          </button>
        </div>
      </template>

      <template v-else>
        <p v-if="loading" class="mt-6 py-8 text-center text-sm text-muted-foreground">加载中...</p>
        <template v-else>
          <label class="mt-4 block text-sm font-medium">飞书主体</label>
          <select v-model="subjectCode" class="mt-1 w-full rounded-md border border-border bg-card px-3 py-2 text-sm">
            <option v-if="!feishuSubjects.length" value="">未配置主体</option>
            <option v-for="s in feishuSubjects" :key="s.code" :value="s.code">{{ s.name }}（{{ s.code }}）</option>
          </select>
          <p v-if="!feishuSubjects.length" class="mt-1 text-xs text-muted-foreground">请先在系统中配置飞书登录应用与主体。</p>

          <label class="mt-4 block text-sm font-medium">评估对象类型</label>
          <select v-model="targetType" class="mt-1 w-full rounded-md border border-border bg-card px-3 py-2 text-sm">
            <option value="all">全员</option>
            <option value="department">部门</option>
            <option value="employee">员工</option>
          </select>

          <div v-if="targetType === 'all'" class="mt-4 rounded-md border border-border bg-accent/30 p-3 text-sm">
            已选择 <span class="font-semibold text-primary">{{ employees.length }}</span> 人（全员）
          </div>

          <template v-else-if="targetType === 'department'">
            <div class="mt-4 flex items-center justify-between">
              <label class="text-sm font-medium">
                部门与成员
                <span class="ml-2 text-xs text-muted-foreground">已选 {{ selectedEmployees.length }} 人</span>
              </label>
            </div>
            <input
              v-model="query"
              type="search"
              class="mt-2 w-full rounded-md border border-border bg-card px-3 py-2 text-sm"
              placeholder="搜索部门或成员姓名"
            />
            <div class="mt-2 max-h-72 space-y-2 overflow-y-auto rounded-md border border-border p-2">
              <details
                v-for="dept in filteredDepartmentOptions"
                :key="dept.id"
                class="rounded-md border border-border bg-card open:bg-accent/20"
              >
                <summary class="flex cursor-pointer list-none items-center gap-2 px-3 py-2 text-sm [&::-webkit-details-marker]:hidden">
                  <input
                    type="checkbox"
                    class="shrink-0"
                    :checked="deptHeaderChecked(dept)"
                    @click.stop
                    @change="toggleDeptSelectAll(dept, ($event.target as HTMLInputElement).checked)"
                  />
                  <span class="font-medium">{{ dept.name || dept.id }}</span>
                  <span class="text-xs text-muted-foreground">（{{ deptEmployeeIds(dept).length }} 人）</span>
                </summary>
                <div class="space-y-2 border-t border-border px-3 py-2 pl-10">
                  <label
                    v-for="emp in employeesInDept(dept)"
                    :key="emp.userId"
                    class="flex cursor-pointer items-center gap-2 text-sm"
                  >
                    <input
                      type="checkbox"
                      :checked="selectedEmployees.includes(emp.userId)"
                      @change="toggleEmployee(emp.userId, ($event.target as HTMLInputElement).checked)"
                    />
                    <span>{{ emp.name }}</span>
                    <span v-if="!emp.assessmentRuleId" class="text-xs text-[var(--warning)]">未绑规则</span>
                  </label>
                  <p v-if="employeesInDept(dept).length === 0" class="text-xs text-muted-foreground">无匹配成员</p>
                </div>
              </details>
              <p v-if="filteredDepartmentOptions.length === 0" class="py-6 text-center text-sm text-muted-foreground">
                暂无部门数据，请先同步员工或检查主体
              </p>
            </div>
          </template>

          <template v-else>
            <div class="mt-4 flex items-center justify-between">
              <label class="text-sm font-medium">
                选择员工
                <span class="ml-2 text-xs text-muted-foreground">已选 {{ selectedEmployees.length }} 人</span>
              </label>
              <button type="button" class="text-xs text-primary hover:underline" @click="toggleSelectAllEmployees">
                {{ allEmployeesSelected ? "取消全选" : "全选" }}
              </button>
            </div>
            <input
              v-model="query"
              type="search"
              class="mt-2 w-full rounded-md border border-border bg-card px-3 py-2 text-sm"
              placeholder="搜索姓名或部门"
            />
            <div class="mt-2 max-h-52 space-y-2 overflow-y-auto rounded-md border border-border p-3">
              <label
                v-for="emp in filteredEmployees"
                :key="emp.userId"
                class="flex cursor-pointer items-center gap-2 text-sm"
              >
                <input
                  type="checkbox"
                  :checked="selectedEmployees.includes(emp.userId)"
                  @change="toggleEmployee(emp.userId, ($event.target as HTMLInputElement).checked)"
                />
                <span>{{ emp.name }}</span>
                <span v-if="emp.departmentName" class="text-muted-foreground">（{{ emp.departmentName }}）</span>
                <span v-if="!emp.assessmentRuleId" class="text-xs text-[var(--warning)]">未绑规则</span>
              </label>
              <p v-if="filteredEmployees.length === 0" class="text-center text-sm text-muted-foreground">无匹配员工</p>
            </div>
          </template>

          <label class="mt-4 block text-sm font-medium">考核月度</label>
          <AssessmentMonthPicker v-model="period" class="mt-1" :items="periods" :disabled="loading" />

          <label class="mt-4 block text-sm font-medium">评分方案</label>
          <select v-model="scoringSchemeId" class="mt-1 w-full rounded-md border border-border bg-card px-3 py-2 text-sm">
            <option value="">请选择评分方案</option>
            <option v-for="s in schemeList" :key="s.id" :value="s.id">
              {{ schemeWeightSummary(s) }}
            </option>
          </select>
          <p class="mt-1 text-xs text-muted-foreground">定义绩效、文化价值观、学习与成长的评分占比</p>
          <p v-if="schemeSelectHint" class="mt-1 text-xs text-[var(--warning)]">{{ schemeSelectHint }}</p>

          <p class="mt-3 text-xs text-muted-foreground">
            考核规则请在「员工管理」中为每位员工绑定；未绑定或规则已停用的员工将无法创建，结果会在下方失败明细中列出。
          </p>

          <p class="mt-2 text-xs text-muted-foreground">将创建 {{ totalSelectedCount }} 名员工的绩效记录</p>

          <div class="mt-6 flex justify-end gap-3">
            <button type="button" class="rounded-md border border-border px-4 py-2 text-sm" @click="close">取消</button>
            <button
              type="button"
              class="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground"
              :disabled="submitting"
              @click="submit"
            >
              {{ submitting ? "提交中..." : "创建" }}
            </button>
          </div>
        </template>
      </template>
    </div>
  </div>
</template>

// legacy/react-client/src/pages/PerformanceListPage/CreatePerformanceDialog.tsx
import { useState, useEffect, useMemo } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { createPerformance } from '@/api';
import { logger } from '@lark-apaas/client-toolkit/logger';
import { axiosForBackend } from '@lark-apaas/client-toolkit/utils/getAxiosForBackend';
import type { CreatePerformanceResponse } from '@shared/api.interface';
import { toast } from 'sonner';
import { Checkbox } from '@/components/ui/checkbox';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Input } from '@/components/ui/input';
import { ChevronsUpDown, Search } from 'lucide-react';
import { cn } from '@/lib/utils';

type TargetType = 'all' | 'department' | 'employee';

interface Department {
  id: string;
  name: string;
  memberCount?: number;
}

interface Employee {
  userId: string;
  name: string;
  departmentName?: string;
}

interface MonthPeriodOption {
  periodKey: string;
  name: string;
}

interface CreatePerformanceDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

const CreatePerformanceDialog = ({ open, onOpenChange, onSuccess }: CreatePerformanceDialogProps) => {
  const [departments, setDepartments] = useState<Department[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [targetType, setTargetType] = useState<TargetType>('employee');
  const [selectedDepartmentIds, setSelectedDepartmentIds] = useState<string[]>([]);
  const [selectedEmployees, setSelectedEmployees] = useState<string[]>([]);
  const [selectedPeriod, setSelectedPeriod] = useState<string>('');
  const [monthPeriodOptions, setMonthPeriodOptions] = useState<MonthPeriodOption[]>([]);
  const [periodPopoverOpen, setPeriodPopoverOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [result, setResult] = useState<CreatePerformanceResponse | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  // 加载部门和员工数据
  useEffect(() => {
    if (open) {
      loadDepartmentsAndEmployees();
    }
  }, [open]);

  // 重置搜索词当目标类型变化时
  useEffect(() => {
    setSearchQuery('');
    setSelectedDepartmentIds([]);
    setSelectedEmployees([]);
  }, [targetType]);

  const loadDepartmentsAndEmployees = async () => {
    setLoading(true);
    try {
      const [empRes, periodsRes] = await Promise.all([
        axiosForBackend({ url: '/api/employees/all', method: 'GET' }),
        axiosForBackend({ url: '/api/performances/create/month-periods', method: 'GET' }).catch(
          (e) => {
            logger.error('加载考核月度失败', e);
            toast.error('加载考核月度列表失败，请确认已维护「周期与评选」中的月度周期');
            return { data: { items: [] as MonthPeriodOption[] } };
          },
        ),
      ]);
      const empData = empRes.data as { items: Employee[] };
      const empList = empData.items || [];
      setEmployees(empList);

      const periodData = periodsRes.data as { items: MonthPeriodOption[] };
      setMonthPeriodOptions(periodData.items ?? []);

      // 从员工数据中提取部门
      const deptMap = new Map<string, Department>();
      empList.forEach((emp) => {
        if (emp.departmentName) {
          const current = deptMap.get(emp.departmentName);
          if (current) {
            current.memberCount = (current.memberCount || 0) + 1;
          } else {
            deptMap.set(emp.departmentName, {
              id: emp.departmentName,
              name: emp.departmentName,
              memberCount: 1,
            });
          }
        }
      });
      setDepartments(Array.from(deptMap.values()));
    } catch (error) {
      logger.error('加载数据失败', error);
      toast.error('加载数据失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  // 根据搜索词筛选员工
  const filteredEmployees = useMemo(() => {
    if (!searchQuery.trim()) return employees;
    const query = searchQuery.toLowerCase();
    return employees.filter(
      (e) =>
        e.name.toLowerCase().includes(query) ||
        (e.departmentName && e.departmentName.toLowerCase().includes(query))
    );
  }, [employees, searchQuery]);

  // 根据搜索词筛选部门
  const filteredDepartments = useMemo(() => {
    if (!searchQuery.trim()) return departments;
    const query = searchQuery.toLowerCase();
    return departments.filter((d) => d.name.toLowerCase().includes(query));
  }, [departments, searchQuery]);

  // 获取已选部门的所有员工姓名
  const selectedDeptEmployeeNames = useMemo(() => {
    const selectedDeptNames = selectedDepartmentIds;
    return employees
      .filter((e) => e.departmentName && selectedDeptNames.includes(e.departmentName))
      .map((e) => e.name);
  }, [employees, selectedDepartmentIds]);

  // 计算总选中人数
  const totalSelectedCount = useMemo(() => {
    if (targetType === 'all') return employees.length;
    if (targetType === 'department') {
      // 去重计数
      const uniqueNames = new Set(selectedDeptEmployeeNames);
      return uniqueNames.size;
    }
    return selectedEmployees.length;
  }, [targetType, employees.length, selectedDeptEmployeeNames, selectedEmployees]);

  // 切换部门选择
  const toggleDepartment = (deptId: string) => {
    setSelectedDepartmentIds((prev) =>
      prev.includes(deptId) ? prev.filter((id) => id !== deptId) : [...prev, deptId]
    );
  };

  // 切换员工选择
  const toggleEmployee = (name: string) => {
    setSelectedEmployees((prev) =>
      prev.includes(name) ? prev.filter((n) => n !== name) : [...prev, name]
    );
  };

  // 全选/取消全选员工
  const toggleSelectAllEmployees = () => {
    const allNames = filteredEmployees.map((e) => e.name);
    const allSelected = allNames.every((name) => selectedEmployees.includes(name));
    if (allSelected) {
      setSelectedEmployees((prev) => prev.filter((name) => !allNames.includes(name)));
    } else {
      setSelectedEmployees((prev) => Array.from(new Set([...prev, ...allNames])));
    }
  };

  // 全选/取消全选部门
  const toggleSelectAllDepartments = () => {
    const allIds = filteredDepartments.map((d) => d.id);
    const allSelected = allIds.every((id) => selectedDepartmentIds.includes(id));
    if (allSelected) {
      setSelectedDepartmentIds((prev) => prev.filter((id) => !allIds.includes(id)));
    } else {
      setSelectedDepartmentIds((prev) => Array.from(new Set([...prev, ...allIds])));
    }
  };

  const resetForm = () => {
    setTargetType('employee');
    setSelectedDepartmentIds([]);
    setSelectedEmployees([]);
    setSelectedPeriod('');
    setSearchQuery('');
    setShowResult(false);
    setResult(null);
  };

  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen) {
      resetForm();
    }
    onOpenChange(newOpen);
  };

  const getSelectedEmployeeNames = (): string[] => {
    if (targetType === 'all') {
      return employees.map((e) => e.name);
    }
    if (targetType === 'department') {
      return Array.from(new Set(selectedDeptEmployeeNames));
    }
    return selectedEmployees;
  };

  const handleSubmit = async () => {
    const employeeNames = getSelectedEmployeeNames();
    if (employeeNames.length === 0) {
      toast.error('请至少选择一名员工');
      return;
    }
    if (!selectedPeriod) {
      toast.error('请选择考核月度');
      return;
    }

    setSubmitting(true);
    try {
      const res = await createPerformance({
        employeeNames,
        period: selectedPeriod,
      });
      setResult(res);
      setShowResult(true);
    } catch (error) {
      logger.error('创建绩效失败', error);
      toast.error('创建绩效失败，请重试');
    } finally {
      setSubmitting(false);
    }
  };

  const handleSuccess = () => {
    handleOpenChange(false);
    onSuccess();
  };

  const failedResults = result?.results.filter((r) => !r.success) ?? [];

  // 判断是否全选
  const isAllEmployeesSelected =
    filteredEmployees.length > 0 &&
    filteredEmployees.every((e) => selectedEmployees.includes(e.name));
  const isAllDepartmentsSelected =
    filteredDepartments.length > 0 &&
    filteredDepartments.every((d) => selectedDepartmentIds.includes(d.id));

  // 获取目标类型标签
  const getTargetTypeLabel = (type: TargetType) => {
    switch (type) {
      case 'all':
        return '全员';
      case 'department':
        return '部门';
      case 'employee':
        return '员工';
    }
  };

  const selectedMonthLabel = useMemo(() => {
    const m = monthPeriodOptions.find((p) => p.periodKey === selectedPeriod);
    if (!selectedPeriod) return null;
    if (m?.name) return `${selectedPeriod} · ${m.name}`;
    return selectedPeriod;
  }, [monthPeriodOptions, selectedPeriod]);

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[600px] max-h-[85vh]">
        <DialogHeader>
          <DialogTitle>创建绩效评估</DialogTitle>
        </DialogHeader>

        {loading ? (
          <div className="py-8 text-center text-muted-foreground">加载中...</div>
        ) : showResult && result ? (
          <div className="space-y-4 py-4">
            <div>
              <h3 className="text-base font-semibold">创建结果</h3>
              <div className="mt-2 space-y-1 text-sm">
                <p>总计: {result.total} 条</p>
                <p className="text-success">成功: {result.successCount} 条</p>
                {result.failCount > 0 && (
                  <p className="text-danger">失败: {result.failCount} 条</p>
                )}
              </div>
            </div>

            {failedResults.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-sm font-semibold text-danger">失败详情</h4>
                <div className="max-h-40 overflow-y-auto space-y-1 rounded-md border border-border p-3">
                  {failedResults.map((r, idx) => (
                    <div key={idx} className="text-sm text-danger">
                      {r.employeeName || r.employeeId}: {r.error}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-4 py-4">
            {/* 评估对象类型选择 */}
            <div className="space-y-2">
              <Label>
                评估对象类型 <span className="text-danger">*</span>
              </Label>
              <Select value={targetType} onValueChange={(v) => setTargetType(v as TargetType)}>
                <SelectTrigger>
                  <SelectValue placeholder="选择评估对象类型" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">全员</SelectItem>
                  <SelectItem value="department">部门</SelectItem>
                  <SelectItem value="employee">员工</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* 根据类型显示对应列表 */}
            {targetType === 'all' && (
              <div className="space-y-2">
                <Label>已选人员</Label>
                <div className="rounded-md border border-border bg-accent/30 p-3">
                  <p className="text-sm">
                    已选择 <span className="font-semibold text-primary">{employees.length}</span> 人
                    （全员）
                  </p>
                </div>
              </div>
            )}

            {targetType === 'department' && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label>
                    选择部门 <span className="text-danger">*</span>
                    <span className="ml-2 text-xs text-muted-foreground">
                      已选择 {selectedDepartmentIds.length} 个部门
                    </span>
                  </Label>
                  <Button variant="ghost" size="sm" onClick={toggleSelectAllDepartments}>
                    {isAllDepartmentsSelected ? '取消全选' : '全选'}
                  </Button>
                </div>

                {/* 搜索框 */}
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="搜索部门名称..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-9"
                  />
                </div>

                <div className="border rounded-md p-2">
                  <ScrollArea className="h-[200px]">
                    <div className="space-y-1">
                      {filteredDepartments.length === 0 ? (
                        <div className="text-center text-sm text-muted-foreground py-4">
                          暂无部门数据
                        </div>
                      ) : (
                        filteredDepartments.map((dept) => (
                          <div
                            key={dept.id}
                            className="flex items-center space-x-2 p-2 hover:bg-accent rounded-sm cursor-pointer"
                            onClick={() => toggleDepartment(dept.id)}
                          >
                            <Checkbox
                              checked={selectedDepartmentIds.includes(dept.id)}
                              onCheckedChange={() => toggleDepartment(dept.id)}
                            />
                            <span className="text-sm flex-1">{dept.name}</span>
                            {dept.memberCount !== undefined && (
                              <span className="text-xs text-muted-foreground">
                                {dept.memberCount} 人
                              </span>
                            )}
                          </div>
                        ))
                      )}
                    </div>
                  </ScrollArea>
                </div>

                {selectedDepartmentIds.length > 0 && (
                  <div className="text-xs text-muted-foreground">
                    预计覆盖 <span className="font-medium text-foreground">{totalSelectedCount}</span> 人
                  </div>
                )}
              </div>
            )}

            {targetType === 'employee' && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label>
                    选择员工 <span className="text-danger">*</span>
                    <span className="ml-2 text-xs text-muted-foreground">
                      已选择 {selectedEmployees.length} 人
                    </span>
                  </Label>
                  <Button variant="ghost" size="sm" onClick={toggleSelectAllEmployees}>
                    {isAllEmployeesSelected ? '取消全选' : '全选'}
                  </Button>
                </div>

                {/* 搜索框 */}
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="搜索姓名或部门..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-9"
                  />
                </div>

                <div className="border rounded-md p-2">
                  <ScrollArea className="h-[200px]">
                    <div className="space-y-1">
                      {filteredEmployees.length === 0 ? (
                        <div className="text-center text-sm text-muted-foreground py-4">
                          暂无员工数据
                        </div>
                      ) : (
                        filteredEmployees.map((emp) => (
                          <div
                            key={emp.userId}
                            className="flex items-center space-x-2 p-2 hover:bg-accent rounded-sm cursor-pointer"
                            onClick={() => toggleEmployee(emp.name)}
                          >
                            <Checkbox
                              checked={selectedEmployees.includes(emp.name)}
                              onCheckedChange={() => toggleEmployee(emp.name)}
                            />
                            <span className="text-sm flex-1">{emp.name}</span>
                            {emp.departmentName && (
                              <span className="text-xs text-muted-foreground">
                                {emp.departmentName}
                              </span>
                            )}
                          </div>
                        ))
                      )}
                    </div>
                  </ScrollArea>
                </div>
              </div>
            )}

            {/* 考核月度（可搜索） */}
            <div className="space-y-2">
              <Label>
                考核月度 <span className="text-danger">*</span>
              </Label>
              <Popover open={periodPopoverOpen} onOpenChange={setPeriodPopoverOpen}>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    role="combobox"
                    aria-expanded={periodPopoverOpen}
                    className={cn(
                      'w-full justify-between font-normal',
                      !selectedPeriod && 'text-muted-foreground',
                    )}
                  >
                    <span className="truncate text-left">
                      {selectedMonthLabel ?? '请选择考核月度（YYYY-MM）'}
                    </span>
                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0" align="start">
                  <Command>
                    <CommandInput placeholder="搜索 YYYY-MM 或名称…" />
                    <CommandList>
                      <CommandEmpty>
                        {monthPeriodOptions.length === 0
                          ? '暂无月度周期，请在「周期与评选」中新增'
                          : '无匹配项'}
                      </CommandEmpty>
                      <CommandGroup>
                        {monthPeriodOptions.map((p) => (
                          <CommandItem
                            key={p.periodKey}
                            value={`${p.periodKey} ${p.name || ''}`}
                            onSelect={() => {
                              setSelectedPeriod(p.periodKey);
                              setPeriodPopoverOpen(false);
                            }}
                          >
                            <span className="font-medium">{p.periodKey}</span>
                            {p.name ? (
                              <span className="text-muted-foreground truncate">{p.name}</span>
                            ) : null}
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
            </div>
          </div>
        )}

        <DialogFooter>
          {showResult ? (
            <Button onClick={handleSuccess}>确定</Button>
          ) : (
            <>
              <Button variant="outline" onClick={() => handleOpenChange(false)}>
                取消
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={
                  submitting ||
                  totalSelectedCount === 0 ||
                  (targetType === 'department' && selectedDepartmentIds.length === 0) ||
                  (targetType === 'employee' && selectedEmployees.length === 0)
                }
              >
                {submitting
                  ? '创建中...'
                  : `创建 (${getTargetTypeLabel(targetType)} ${totalSelectedCount}人)`}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default CreatePerformanceDialog;
